[default]
; 波特率设置  
baud_rate=9600
; 超时(XXX)ms后无信号 (正常情况下请填写>=100的值, 默认500), 通道置为0;			该值若为0   通道则立刻置为0
timeout=500
; 组合模式  0: ASCII模式  1: 16进制模式
combo_mode=1
; 开始帧
start_bits=02
; 数据帧长度
frame_length=14


;读卡器读到的卡号不在config中时，卡号数据会自动写入配置文件，无需手动配置
[ComboKeys]
