[default]
# 心跳间隔 (秒) 0表示不发送心跳
heartbeat_interval = 5  

# 心跳服务器 （设计供运维管家进程守护使用） 不填默认使用数据上报服务器
heartbeat_ip=127.0.0.1
heartbeat_port=32001

# 数据上报服务器
server_ip=127.0.0.1
server_port=12321

# 本机UDP端口
local_port=12333
# 上报时间间隔 (s)
report_interval=3