[default]
write_wait_ms = 60
# 本地地址
local_port = 12001

# 远程地址
remote_ip = 127.0.0.1
remote_port = 13001

# TCP专用配置
# TCP重连间隔
tcp_reconnect_interval_ms = 3000

# 是否启用TCP keepalive
tcp_keepalive = true  

[device_1]
# 该设备使用UDP
protocol = udp

write_wait_ms = 50
remote_ip = 127.0.0.1
remote_port = 4001
local_port = 5001

[device_2]
# 该设备使用TCP
protocol = tcp

write_wait_ms = 50
remote_ip = 127.0.0.1
remote_port = 4002
local_port = 5002


[InputMapping]
0 = Button_00
1 = Button_01
2 = Button_02

[OutputMapping]
0 = Button_00
1 = Button_01
2 = Button_02